### ISSUE TITLE
Feedback usernames

### ISSUE THREAD

**Issue by amazansky** [PlanHubMe/PlanHub#372]
In feedback, when @willweinstein had his old username `hexrHazHexdYoo`, it said that as the feedback name. Now that we did a no name-change commit and changed the name back, it still says hexrHazHexdYoo. I think I know why this is (it just saves the name at the time being) and can we change it?

**Comment by thatoddmailbox** [comment]
@RobotXLabs You are correct; feedback saves the user's name and username at time of submission. This is done so that we don't have to make another database lookup for _every feedback_ to figure out the name and username. This is also the reason why adding badges to feedback is difficult (level and type are not saved)

I could write a script to check the username and update the name, though...

**Comment by willbarkoff** [comment]
@thatoddmailbox @RobotXLabs Is this really necessary? The only person that changed there name was @willweinstein, and we all know who hexrHazHexdYoo is.

**Comment by amazansky** [comment]
I mean, its okay, but just a bit weird, although I suppose we could just keep it.

**Comment by thatoddmailbox** [comment]
@RobotXLabs @nywillb I will look into doing a hexr_SQL script using a `JOIN` because ~~I have too much time~~ __THIS IS A VERY IMPORTANT FEATURE AND TOP PRIORITY__

**Comment by amazansky** [comment]
Yes. Yes it is.

**Comment by willbarkoff** [comment]
@thatoddmailbox Also, why does it now say "PlanHub Member" above our comments? ^^^^

**Comment by thatoddmailbox** [comment]
@nywillb because we are all in the PlanHub organization, so GitHub adds that to our comments (if someone outside of PlanHub commented, it wouldn't say that)

**Comment by thatoddmailbox** [comment]
I've run a script on the database, and all feedback names have been updated!
